version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=medweb

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=medweb
      - USE_DOCKER=yes
      - REMOTE_ADDRESS=192.168.99.1
      # REMOTE_ADDRESS  is use django debug toolbar, check
      # http://stackoverflow.com/questions/10517765/django-debug-toolbar-not-showing-up
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
