version: '2'


services:
  # DJANGO BUILD SPECIFICATIONS
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=medweb
      - POSTRES_PASSWORD=medweb


  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: .env_test  # For hidden variables like the mailchimp api key


    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres


  # WORDPRESS BUILD
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  php:
     build:
       context: .
       dockerfile: ./compose/wordpress-php/Dockerfile
     environment:
       PHP_SITE_NAME: http://localhost/blog
       PHP_HOST_NAME: localhost:8000
       #PHP_DOCROOT: blog # Relative path inside the /var/www/html/ directory.
       PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
       PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       #WORDPRESS_DEBUG: 1 # 1 for true
       WP_HOME: http://localhost/blog
       WP_SITEURL: http://localhost/blog
       REDIS_HOST: redis
     volumes:
       - ./wordpress/:/var/www/html

  nginx:
    build: ./compose/nginx
    environment:
      NGINX_SERVER_NAME: 192.168.99.100
      NGINX_UPSTREAM_NAME: php
#      NGINX_DOCROOT: public # Relative path inside the /var/www/html/ directory.
    volumes_from:
      - php
    ports:
      - "80:80"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8002:80"



#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
#    ports:
#      - "8003:8983"

volumes:
    db_data:
    postgres_data_dev:
    postgres_backup_dev:

