FROM python:3.5

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]

#ADDED BY ME - NEED TO FORMAT BETTER
RUN apt-get update \
    && apt-get install -y nodejs \
    && apt-get install -y npm

RUN npm install -g bower

RUN apt-get install ruby-full -y

RUN apt-get install rubygems -y

RUN gem install bourbon

# Symlink Bower
RUN ln -s /usr/bin/nodejs /usr/bin/node

#RUN bower install --allow-root   #Install bower package dependencies.
