# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import medweb.homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20161122_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.Person')),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=2000)),
                ('call_time', models.DateTimeField(blank=True, null=True)),
                ('current_system', models.CharField(blank=True, max_length=255)),
                ('ehr_support_vendors', models.IntegerField(blank=True, null=True)),
                ('ehr_support_personnel', models.IntegerField(blank=True, null=True)),
                ('ehr_likes', models.CharField(blank=True, max_length=2000)),
                ('ehr_dislikes', models.CharField(blank=True, max_length=2000)),
                ('hr_providers', models.IntegerField(blank=True, null=True)),
                ('hr_it_staff', models.IntegerField(blank=True, null=True)),
                ('hr_other_staff', models.IntegerField(blank=True, null=True)),
                ('ehr_providers', models.IntegerField(blank=True, null=True)),
                ('ehr_mas', models.IntegerField(blank=True, null=True)),
                ('ehr_receiptionists', models.IntegerField(blank=True, null=True)),
                ('rcm_billers', models.IntegerField(blank=True, null=True)),
                ('rcm_coders', models.IntegerField(blank=True, null=True)),
                ('rcm_scribes', models.IntegerField(blank=True, null=True)),
                ('rcm_collectors', models.IntegerField(blank=True, null=True)),
                ('clearinghouse', models.CharField(blank=True, max_length=512)),
                ('billing_company', models.CharField(blank=True, max_length=512)),
                ('days_to_collect', models.IntegerField(blank=True, null=True)),
                ('percent_ars', models.FloatField(blank=True, null=True)),
                ('available_rooms', models.IntegerField(blank=True, null=True)),
                ('revenue_labs', models.IntegerField(blank=True, null=True)),
                ('doctors_recruit', models.CharField(blank=True, max_length=2000)),
                ('total_revenue', models.FloatField(blank=True, null=True)),
                ('referral', models.CharField(blank=True, max_length=255)),
                ('monthly_newsletter', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='message',
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=models.CharField(max_length=15, null=True, validators=[medweb.homepage.models.phone_validator]),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_phone',
            field=models.CharField(max_length=15, null=True, validators=[medweb.homepage.models.phone_validator]),
        ),
    ]
