# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import medweb.homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20161123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[medweb.homepage.models.phone_validator]),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[medweb.homepage.models.phone_validator]),
        ),
    ]
