# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20161123_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='ehr_admin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
