# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20161124_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='ehr_receiptionists',
            new_name='ehr_receptionists',
        ),
    ]
