# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20161124_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 25, 19, 52, 34, 579674, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 25, 19, 52, 44, 658180, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
