# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20161125_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
