# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_person_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
