# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20161207_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='current_system',
            field=models.CharField(blank=True, choices=[('Cerner', 'Cerner'), ('Epic', 'Epic'), ('Allscripts', 'Allscripts'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='group_type',
            field=models.CharField(blank=True, choices=[('MS', 'MS'), ('Solo', 'Solo'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='net_income_status',
            field=models.CharField(blank=True, choices=[('Decreased', 'Decreased'), ('Same', 'Stayed the Same'), ('Increased', 'Increased')], max_length=255),
        ),
    ]
