# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_randomreferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomreferral',
            name='referral',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
