# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20161229_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomreferral',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 30, 0, 13, 34, 779329, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
