# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20170102_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='rcm_scribes',
            new_name='ehr_scribes',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='hr_providers',
            new_name='hr_staff',
        ),
    ]
