# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_remove_evaluation_revenue_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
