# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20170103_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='total_revenue',
            field=models.CharField(blank=True, choices=[('1 - 499,999', '1 - 499,999'), ('500,000 - 999,999', '500,000 - 999,999'), ('1,000,000 - 1,999,999', '1,000,000 - 1,999,999'), ('2,000,000 - 4,999,999', '2,000,000 - 4,999,999'), ('5,000,000 - 9,999,999', '5,000,000 - 9,999,999'), ('10,000,000+', '10,000,000+')], max_length=255, null=True),
        ),
    ]
